### ISSUE TITLE
Beta releases

### ISSUE THREAD

**Issue by mwf** [fasthttp/websocket#22]
Hi!

```
v1.4.3-beta.5
v1.4.3-beta.4
v1.4.3-beta.3
v1.4.3-beta.2
v1.4.3-beta.1
```

Why so many beta-releases?
Are they used to test something?If not - what's the purpose? 

Could you please tag some stable release if they are good enough for production use? :)

**Comment by savsgio** [comment]
Hi @mwf,

The beta releases are versions to try to keep dependencies like fasthttp updated, because the philosophy of this fork is to keep the same versioning of gorilla/websocket, but they take a long time to release a new versions.

So, dont't worry about betas because the are stable for production use ! 😉 

When the gorilla/websocket release the version v1.4.3, we will release the same version here.

Note: Maybe the name `rc` is more reliable than `beta`.

Thanks!

**Comment by gavv** [comment]
@savsgio 

Hi, could you clarify if those `beta` and `rc` tags are safe to use in regard that they wont be removed in future?

Background: https://github.com/gavv/httpexpect/issues/99

**Comment by savsgio** [comment]
Hi @gavv,

The `beta` and `rc` versions are intermediet versions between version of gorilla websocket versioning and fasthttp, because the idea of this repository is has the same versioning of gorilla, but fasthttp has release versions more frencuently.

So the `rc` are stable to use in production.
